name: Deploy Pages (smart)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Decide whether to build from /frontend or deploy static /docs
      - name: Decide build path
        id: paths
        shell: bash
        run: |
          if [ -f frontend/package.json ]; then
            echo "do_build=true" >> "$GITHUB_OUTPUT"
            echo "build_path=frontend/dist" >> "$GITHUB_OUTPUT"
          else
            echo "do_build=false" >> "$GITHUB_OUTPUT"
            echo "build_path=docs" >> "$GITHUB_OUTPUT"
          fi

      # Only set up Node & build if /frontend/package.json exists
      - name: Setup Node
        if: steps.paths.outputs.do_build == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build (frontend)
        if: steps.paths.outputs.do_build == 'true'
        working-directory: frontend
        run: |
          npm ci || npm install
          npm run build

      # Upload the site artifact (either docs/ or frontend/dist)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.paths.outputs.build_path }}

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
